spring:
  cloud:
    gateway:
      routes:
        - id: httpbin
          uri: http://httpbin.org/anything
          predicates:
            - Path=/anything/**
        - id: mockbin
          uri: https://mockbin.org
          predicates:
            - Path=/get