spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: http://localhost:8081/api/inventory
          predicates:
            - Path=/api/inventory/**
        - id: order-service
          uri: http://localhost:8082/api/order
          predicates:
            - Path=/api/order/**
        - id: product-service
          uri: http://localhost:8083/api/product
          predicates:
            - Path=/api/product/**
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}